// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/friend_requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户收到的所有待处理好友请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "获取待处理好友请求",
                "responses": {
                    "200": {
                        "description": "好友请求列表",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.FriendRequestsResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/friend_requests/{request_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "接受或拒绝好友请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "回复好友请求",
                "parameters": [
                    {
                        "type": "string",
                        "description": "好友请求ID",
                        "name": "request_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "回复参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ReplyFriendRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "回复成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/friends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有好友",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "获取好友列表",
                "responses": {
                    "200": {
                        "description": "好友列表",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.FriendsListResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "发送好友请求给指定用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "添加好友",
                "parameters": [
                    {
                        "description": "添加好友请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.AddFriendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "好友请求已发送",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/friends/{friend_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从好友列表中删除指定好友",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "删除好友",
                "parameters": [
                    {
                        "type": "string",
                        "description": "好友ID",
                        "name": "friend_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/group/{id}/members/{member_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主修改群组成员的角色（管理员/普通成员）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "修改群组成员角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "成员ID",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ChangeGroupMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/group_requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主获取待处理的群组加入请求列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取待处理群组加入请求",
                "parameters": [
                    {
                        "description": "群组ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.GetPendingGroupJoinRequestsBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "加入请求列表",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.GroupJoinRequestsResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "发送加入群组的申请请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "申请加入群组",
                "parameters": [
                    {
                        "description": "加入群组请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.JoinGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "申请已发送",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/group_requests/{request_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主接受或拒绝加入群组的请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "回复群组加入请求",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求ID",
                        "name": "request_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "回复参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ReplyGroupJoinRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "回复成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户加入的所有群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取用户群组列表",
                "responses": {
                    "200": {
                        "description": "群组列表",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.UserGroupsResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "创建群组",
                "parameters": [
                    {
                        "description": "创建群组请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "群组创建成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CreateGroupResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据群组ID获取群组详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取群组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "群组信息",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.GroupInfo"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{id}/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定群组的所有成员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取群组成员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "群组成员列表",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.GroupMembersResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{id}/members/me": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户退出指定的群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "退出群组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{id}/members/{member_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主或管理员移除群组成员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "移除群组成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "成员ID",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "移除成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登录获取 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回 Token",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "发送消息给指定用户或群组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "description": "发送消息请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息发送成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/offline": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的离线消息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "获取离线消息",
                "responses": {
                    "200": {
                        "description": "离线消息列表",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.OfflineMessagesResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/read": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将当前用户的所有消息标记为已读状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "标记所有消息已读",
                "responses": {
                    "200": {
                        "description": "标记成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/unread/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的未读消息数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "获取未读消息数",
                "responses": {
                    "200": {
                        "description": "未读消息数",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.UnreadCountResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}/read": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定消息标记为已读状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "标记消息已读",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "标记成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.CommonResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "创建新用户账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户ID获取用户详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.UserInfo"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "services_gateway_handler.AddFriendRequest": {
            "type": "object",
            "required": [
                "friend_id"
            ],
            "properties": {
                "friend_id": {
                    "type": "string",
                    "example": "123456"
                },
                "reason": {
                    "type": "string",
                    "example": "想加你为好友"
                }
            }
        },
        "services_gateway_handler.ChangeGroupMemberRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "services_gateway_handler.CommonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "services_gateway_handler.CreateGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "这是一个技术交流群"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/group.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "技术交流群"
                }
            }
        },
        "services_gateway_handler.CreateGroupResponse": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "string",
                    "example": "789012"
                },
                "name": {
                    "type": "string",
                    "example": "技术交流群"
                }
            }
        },
        "services_gateway_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "services_gateway_handler.FriendInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "id": {
                    "type": "string",
                    "example": "123456789"
                },
                "name": {
                    "type": "string",
                    "example": "frienduser"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "tele": {
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "services_gateway_handler.FriendRequestInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1704067200
                },
                "from_uid": {
                    "type": "string",
                    "example": "123456789"
                },
                "from_user": {
                    "$ref": "#/definitions/services_gateway_handler.UserInfo"
                },
                "id": {
                    "type": "string",
                    "example": "987654321"
                },
                "reason": {
                    "type": "string",
                    "example": "想加你为好友"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "to_uid": {
                    "type": "string",
                    "example": "987654321"
                }
            }
        },
        "services_gateway_handler.FriendRequestsResponse": {
            "type": "object",
            "properties": {
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_gateway_handler.FriendRequestInfo"
                    }
                }
            }
        },
        "services_gateway_handler.FriendsListResponse": {
            "type": "object",
            "properties": {
                "friends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_gateway_handler.FriendInfo"
                    }
                }
            }
        },
        "services_gateway_handler.GetPendingGroupJoinRequestsBody": {
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "group_id": {
                    "type": "string",
                    "example": "789012"
                }
            }
        },
        "services_gateway_handler.GroupInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1704067200
                },
                "description": {
                    "type": "string",
                    "example": "这是一个技术交流群"
                },
                "id": {
                    "type": "string",
                    "example": "789012"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/group.jpg"
                },
                "member_count": {
                    "type": "integer",
                    "example": 50
                },
                "name": {
                    "type": "string",
                    "example": "技术交流群"
                },
                "owner_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "type": {
                    "type": "string",
                    "example": "public"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "services_gateway_handler.GroupJoinRequestInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1704067200
                },
                "group_id": {
                    "type": "string",
                    "example": "789012"
                },
                "id": {
                    "type": "string",
                    "example": "987654321"
                },
                "reason": {
                    "type": "string",
                    "example": "想加入群组"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "user_avatar": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "user_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "user_name": {
                    "type": "string",
                    "example": "applicant"
                }
            }
        },
        "services_gateway_handler.GroupJoinRequestsResponse": {
            "type": "object",
            "properties": {
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_gateway_handler.GroupJoinRequestInfo"
                    }
                }
            }
        },
        "services_gateway_handler.GroupMembersResponse": {
            "type": "object",
            "properties": {
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_gateway_handler.MemberInfo"
                    }
                }
            }
        },
        "services_gateway_handler.JoinGroupRequest": {
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "group_id": {
                    "type": "string",
                    "example": "789012"
                },
                "reason": {
                    "type": "string",
                    "example": "想加入群组"
                }
            }
        },
        "services_gateway_handler.LoginRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "user123"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "tele": {
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "services_gateway_handler.LoginResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "testuser"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "services_gateway_handler.MemberInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "joined_at": {
                    "type": "integer",
                    "example": 1704067200
                },
                "name": {
                    "type": "string",
                    "example": "member1"
                },
                "nickname": {
                    "type": "string",
                    "example": "群成员1"
                },
                "role": {
                    "type": "string",
                    "example": "member"
                },
                "user_id": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "services_gateway_handler.MessageInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "你好"
                },
                "is_read": {
                    "type": "boolean",
                    "example": false
                },
                "is_revoked": {
                    "type": "boolean",
                    "example": false
                },
                "msg_id": {
                    "type": "string",
                    "example": "msg123456"
                },
                "msg_type": {
                    "type": "string",
                    "example": "text"
                },
                "read_at": {
                    "type": "integer",
                    "example": 1704067200
                },
                "receiver_id": {
                    "type": "string",
                    "example": "987654321"
                },
                "sender_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "services_gateway_handler.OfflineMessagesResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_gateway_handler.MessageInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "services_gateway_handler.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "tele"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "user123"
                },
                "name": {
                    "type": "string",
                    "example": "testuser"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "tele": {
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "services_gateway_handler.RegisterResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "testuser"
                },
                "user_id": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "services_gateway_handler.ReplyFriendRequestBody": {
            "type": "object",
            "properties": {
                "accept": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "services_gateway_handler.ReplyGroupJoinRequestBody": {
            "type": "object",
            "properties": {
                "accept": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "services_gateway_handler.SendMessageRequest": {
            "type": "object",
            "required": [
                "content",
                "msg_type",
                "receiver_id"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "你好"
                },
                "msg_type": {
                    "type": "string",
                    "example": "text"
                },
                "receiver_id": {
                    "type": "string",
                    "example": "123456"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "services_gateway_handler.SendMessageResponse": {
            "type": "object",
            "properties": {
                "msg_id": {
                    "type": "string",
                    "example": "msg123456"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "services_gateway_handler.UnreadCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "group_counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                }
            }
        },
        "services_gateway_handler.UserGroupsResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services_gateway_handler.GroupInfo"
                    }
                }
            }
        },
        "services_gateway_handler.UserInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "created_at": {
                    "type": "integer",
                    "example": 1704067200
                },
                "id": {
                    "type": "string",
                    "example": "123456789"
                },
                "name": {
                    "type": "string",
                    "example": "testuser"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "tele": {
                    "type": "string",
                    "example": "13800138000"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1704067200
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "IM 即时通讯系统 API",
	Description:      "IM 即时通讯系统 Gateway 服务 API 文档，包含用户认证、好友管理、群组管理、消息系统等接口。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
